FROM python:3.9

WORKDIR /excel

COPY requirements.txt .

RUN python -m pip install -r requirements.txt

COPY . .

#RUN python manage.py migrate



EXPOSE 8000


CMD ["python", "manage.py", "runserver", "host.docker.internal:8011"]
#CMD ["python", "manage.py", "runserver"]


