version: '3.9'
services:
  web:
    container_name: crm-tool-1
    build:
      context: .
      dockerfile: dockerfile
    environment:
      -DATABASE_HOST=host.docker.internal
    ports:
      - "8011:8000"
    #volumes:
     # - .:/excel
    depends_on:
      - db
    extra_hosts:
    - "host.docker.internal:host-gateway"
     

    #command: sh -c 'wait-for-it db:5431 -- python manage.py runserver 0.0.0.0:8000'
    restart: on-failure:5
    networks:
      - crm-1_my-network


  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=jakobstinnes
      - POSTGRES_PASSWORD=Falkenstein
      - POSTGRES_DB=jakob  # Specify the desired database name here
      - DATABASE_HOST=host.docker.internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-1_my-network
    ports:
      - 5431:5432
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  crm-1_my-network:
    driver: bridge

volumes:
  postgres_data:






# version: '3.9'
# services:
#   web:
#     container_name: crm-tool
#     build:
#       context: .
#       dockerfile: dockerfile
#     ports:
#       - "8001:8000"
#     volumes:
#       - /volume1/docker/crm-tool
#     depends_on:
#       - db
#     command: python manage.py runserver 0.0.0.0:8000
#     restart: on-failure:5

#   db:
#     image: postgres:13
#     container_name: crm-db
#     environment:
#       - POSTGRES_USER=jakobstinnes
#       - POSTGRES_PASSWORD=Falkenstein
#       - POSTGRES_DB=jakob
#     user: 1026:100
#     volumes:
#       - /volume1/docker/crm-tool/data:rw
#     restart: on-failure:5

# volumes:
#   postgres_data:
