# Generated by Django 3.2.18 on 2023-05-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('straße', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('stadt', models.CharField(max_length=100)),
                ('telefon_primär', models.CharField(max_length=20)),
                ('telefon_sekundär', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('objekt', models.CharField(max_length=100)),
                ('anlage', models.CharField(max_length=100)),
                ('dach', models.CharField(max_length=100)),
                ('infos', models.TextField()),
                ('speicher', models.TextField(max_length=100)),
                ('interesse', models.TextField(max_length=100)),
                ('jährlicher_stromverbrauch', models.TextField(max_length=100)),
                ('anfrage_über', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('kunden_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
